import { Palette, SpriteDefinition, TextureGrid } from '../grid';
import { ENTITY_SPRITES } from './entities';

/**
 * UI art as text grids: a tiny digit font, 16x16 icons, one 24x24 nine-slice
 * panel shape (wood and stone are the same grid through different palettes)
 * and the 32x32 title gem. Everything here rides in the JS bundle like the
 * rest of the art — the UI ships zero image files too.
 */

// ------------------------------------------------------------- digit font

export const FONT_PALETTE: Palette = { x: '#fff3d6' };

/**
 * 3x5 glyphs: digits, uppercase letters and a little punctuation. Space is
 * not a glyph — the painter just advances the cursor. ('O' intentionally
 * shares the '0' shape; at 3x5 there is only one honest way to draw it.)
 */
export const PIXEL_FONT: Record<string, TextureGrid> = {
  '0': ['xxx', 'x.x', 'x.x', 'x.x', 'xxx'],
  '1': ['.x.', 'xx.', '.x.', '.x.', 'xxx'],
  '2': ['xxx', '..x', 'xxx', 'x..', 'xxx'],
  '3': ['xxx', '..x', '.xx', '..x', 'xxx'],
  '4': ['x.x', 'x.x', 'xxx', '..x', '..x'],
  '5': ['xxx', 'x..', 'xxx', '..x', 'xxx'],
  '6': ['xxx', 'x..', 'xxx', 'x.x', 'xxx'],
  '7': ['xxx', '..x', '.x.', '.x.', '.x.'],
  '8': ['xxx', 'x.x', 'xxx', 'x.x', 'xxx'],
  '9': ['xxx', 'x.x', 'xxx', '..x', 'xxx'],
  '/': ['..x', '..x', '.x.', 'x..', 'x..'],
  A: ['xxx', 'x.x', 'xxx', 'x.x', 'x.x'],
  B: ['xx.', 'x.x', 'xx.', 'x.x', 'xx.'],
  C: ['xxx', 'x..', 'x..', 'x..', 'xxx'],
  D: ['xx.', 'x.x', 'x.x', 'x.x', 'xx.'],
  E: ['xxx', 'x..', 'xx.', 'x..', 'xxx'],
  F: ['xxx', 'x..', 'xx.', 'x..', 'x..'],
  G: ['xxx', 'x..', 'x.x', 'x.x', 'xxx'],
  H: ['x.x', 'x.x', 'xxx', 'x.x', 'x.x'],
  I: ['xxx', '.x.', '.x.', '.x.', 'xxx'],
  J: ['..x', '..x', '..x', 'x.x', 'xxx'],
  K: ['x.x', 'x.x', 'xx.', 'x.x', 'x.x'],
  L: ['x..', 'x..', 'x..', 'x..', 'xxx'],
  M: ['x.x', 'xxx', 'xxx', 'x.x', 'x.x'],
  N: ['xxx', 'x.x', 'x.x', 'x.x', 'x.x'],
  O: ['xxx', 'x.x', 'x.x', 'x.x', 'xxx'],
  P: ['xxx', 'x.x', 'xxx', 'x..', 'x..'],
  Q: ['xxx', 'x.x', 'x.x', 'xxx', '..x'],
  R: ['xxx', 'x.x', 'xx.', 'x.x', 'x.x'],
  S: ['.xx', 'x..', '.x.', '..x', 'xx.'],
  T: ['xxx', '.x.', '.x.', '.x.', '.x.'],
  U: ['x.x', 'x.x', 'x.x', 'x.x', 'xxx'],
  V: ['x.x', 'x.x', 'x.x', 'x.x', '.x.'],
  W: ['x.x', 'x.x', 'xxx', 'xxx', 'x.x'],
  X: ['x.x', 'x.x', '.x.', 'x.x', 'x.x'],
  Y: ['x.x', 'x.x', '.x.', '.x.', '.x.'],
  Z: ['xxx', '..x', '.x.', 'x..', 'xxx'],
  // Diacritics get the top row; the letter squeezes into the remaining four.
  '\u00c5': ['.x.', 'xxx', 'x.x', 'xxx', 'x.x'],
  '\u00c4': ['x.x', 'xxx', 'x.x', 'xxx', 'x.x'],
  '\u00d6': ['x.x', 'xxx', 'x.x', 'x.x', 'xxx'],
  '\u00dc': ['x.x', '...', 'x.x', 'x.x', 'xxx'],
  '!': ['.x.', '.x.', '.x.', '...', '.x.'],
  '?': ['xxx', '..x', '.xx', '...', '.x.'],
  "'": ['.x.', '.x.', '...', '...', '...'],
};

// ------------------------------------------------------------------ panels

/** Art pixels from each panel edge that must never stretch (nine-slice). */
export const PANEL_CORNER = 2;

const PANEL_SHAPE: TextureGrid = (() => {
  const top = 'o'.repeat(24);
  const lightRow = `o${'l'.repeat(22)}o`;
  const bodyRow = `ol${'w'.repeat(20)}do`;
  const darkRow = `o${'d'.repeat(22)}o`;
  return [top, lightRow, ...Array.from({ length: 20 }, () => bodyRow), darkRow, top];
})();

export const PANELS: Record<'wood' | 'stone', SpriteDefinition> = {
  // 'wood' is the main UI panel — now a light-stone grey.
  wood: {
    frames: [PANEL_SHAPE],
    palette: { o: '#3f444c', l: '#d3d8de', w: '#9aa0a9', d: '#71767e' },
  },
  stone: {
    frames: [PANEL_SHAPE],
    palette: { o: '#1c1f26', l: '#6a7280', w: '#4a5160', d: '#333845' },
  },
};

// ------------------------------------------------------------------- icons

const COIN: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '.....oooooo.....',
      '....oggggggo....',
      '...ogglgggggo...',
      '..ogglgggggddo..',
      '..oglgggggggdo..',
      '..oglgggggggdo..',
      '..oglgggggggdo..',
      '..ogggggggggdo..',
      '..oggggggggddo..',
      '...ogggggggdo...',
      '....oggggddo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
  ],
  palette: { o: '#8a5a1a', g: '#ffcf3f', l: '#ffe58a', d: '#cc9c1f' },
};

const CRATE: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '.oooooooooooooo.',
      '.olllllllllllwo.',
      '.olwwwwwwwwwwdo.',
      '.olwwwwwwwwwwdo.',
      '.oddddddddddddo.',
      '.olwwwwwwwwwwdo.',
      '.olwwwwwwwwwwdo.',
      '.oddddddddddddo.',
      '.olwwwwwwwwwwdo.',
      '.olwwwwwwwwwwdo.',
      '.oddddddddddddo.',
      '.oooooooooooooo.',
      '................',
      '................',
    ],
  ],
  palette: { o: '#3a2416', l: '#b8804a', w: '#8a5a30', d: '#5c3a1e' },
};

/**
 * Battery shell with a hollow inside: the HUD paints the charge as a coloured
 * fill *behind* this icon, showing through the transparent interior.
 */
const BATTERY: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '.oooooooooooo...',
      '.o..........o...',
      '.o..........ott.',
      '.o..........ott.',
      '.o..........ott.',
      '.o..........ott.',
      '.o..........o...',
      '.oooooooooooo...',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { o: '#23262e', t: '#aeb6bf' },
};

/** Where the charge fill goes, in icon art pixels. */
export const BATTERY_INTERIOR = { x: 2, y: 5, w: 10, h: 6 };

const DEPTH: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '......aaaa......',
      '......aaaa......',
      '......aaaa......',
      '......aaaa......',
      '......aaaa......',
      '......aaaa......',
      '..aaaaaaaaaaaa..',
      '...aaaaaaaaaa...',
      '....aaaaaaaa....',
      '.....aaaaaa.....',
      '......aaaa......',
      '.......aa.......',
      '................',
    ],
  ],
  palette: { a: '#9fd0ff' },
};

const PICKAXE: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '....mmmmmmmm....',
      '..mm...mm...mm..',
      '.mm....hh....mm.',
      '.m.....hh.....m.',
      '.......hh.......',
      '.......hh.......',
      '.......hh.......',
      '.......hh.......',
      '.......hh.......',
      '.......hh.......',
      '.......hh.......',
      '.......hh.......',
      '................',
      '................',
    ],
  ],
  palette: { m: '#aeb6bf', h: '#8a5a30' },
};

const LIGHTNING: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '.......yyyy.....',
      '......yyyy......',
      '.....yyyy.......',
      '....yyyyyyy.....',
      '......yyyy......',
      '.....yyyy.......',
      '....yyyy........',
      '...yyyy.........',
      '..yyy...........',
      '..yy............',
      '..y.............',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { y: '#ffe36e' },
};

const BLAST: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '.......g........',
      '...g...g...g....',
      '....g..g..g.....',
      '.....ggggg......',
      '...ggwwwwwgg....',
      'gggggwwwwwggggg.',
      '...ggwwwwwgg....',
      '.....ggggg......',
      '....g..g..g.....',
      '...g...g...g....',
      '.......g........',
      '................',
      '................',
    ],
  ],
  palette: { g: '#ffa53c', w: '#fff7d1' },
};

const STAR: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '.......yy.......',
      '.......yy.......',
      '......yyyy......',
      '..yyyyyyyyyyyy..',
      '...yyyyyyyyyy...',
      '....yyyyyyyy....',
      '....yyyyyyyy....',
      '...yyy....yyy...',
      '..yy........yy..',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { y: '#ffe36e' },
};

const Z_KEY: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '..oooooooooooo..',
      '.occcccccccccco.',
      '.occcccccccccco.',
      '.occczzzzzzccco.',
      '.occccccczzccco.',
      '.occccczzccccco.',
      '.occczzccccccco.',
      '.occczzzzzzccco.',
      '.occcccccccccco.',
      '.occcccccccccco.',
      '..oooooooooooo..',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { o: '#2b2b35', c: '#e8e0d0', z: '#2b2b35' },
};

/**
 * The wide segmented battery (the HUD's real battery). The interior is
 * transparent; the painter draws up to five charge blocks behind it using
 * BATTERY_SEGMENTS, so the shell's outline stays crisp on top.
 */
const BATTERY_WIDE: SpriteDefinition = {
  frames: [
    [
      'ooooooooooooooooooooooo...',
      'o.....................o...',
      'o.....................o...',
      'o.....................ott.',
      'o.....................ott.',
      'o.....................ott.',
      'o.....................ott.',
      'o.....................ott.',
      'o.....................ott.',
      'o.....................o...',
      'o.....................o...',
      'ooooooooooooooooooooooo...',
    ],
  ],
  palette: { o: '#23262e', t: '#aeb6bf' },
};

/** Segment geometry inside BATTERY_WIDE, in art pixels. */
export const BATTERY_SEGMENTS = { x: 2, y: 2, w: 3, h: 8, gap: 1, count: 5 };

const X_KEY: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '..oooooooooooo..',
      '.occcccccccccco.',
      '.occcccccccccco.',
      '.occcxccccxccco.',
      '.occccxccxcccco.',
      '.occcccxxccccco.',
      '.occcccxxccccco.',
      '.occccxccxcccco.',
      '.occcxccccxccco.',
      '.occcccccccccco.',
      '..oooooooooooo..',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { o: '#2b2b35', c: '#e8e0d0', x: '#2b2b35' },
};

/** The four arrow keys as one compact cluster (controls legend). */
const ARROWS: SpriteDefinition = {
  frames: [
    [
      '................',
      '.......aa.......',
      '......aaaa......',
      '.....aaaaaa.....',
      '.......aa.......',
      '................',
      '...aa......aa...',
      '..aaa......aaa..',
      '.aaaa......aaaa.',
      '..aaa......aaa..',
      '...aa......aa...',
      '................',
      '.......aa.......',
      '.....aaaaaa.....',
      '......aaaa......',
      '.......aa.......',
    ],
  ],
  palette: { a: '#e8e0d0' },
};

const PAUSE: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { b: '#fff3d6' },
};

const PLUS: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '......pppp......',
      '......pppp......',
      '......pppp......',
      '..pppppppppppp..',
      '..pppppppppppp..',
      '......pppp......',
      '......pppp......',
      '......pppp......',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  palette: { p: '#57c04a' },
};

const DRILL_DOWN: SpriteDefinition = {
  frames: [
    [
      '................',
      '..mmmmmmm.......',
      '.mm..hh..mm.....',
      '.....hh.........',
      '.....hh.........',
      '.....hh.........',
      '.....hh.........',
      '................',
      '..........aa....',
      '..........aa....',
      '.......aaaaaaaa.',
      '........aaaaaa..',
      '.........aaaa...',
      '..........aa....',
      '................',
      '................',
    ],
  ],
  palette: { m: '#aeb6bf', h: '#8a5a30', a: '#9fd0ff' },
};

const WARNING: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '.......tt.......',
      '......tttt......',
      '......tttt......',
      '.....ttkktt.....',
      '.....ttkktt.....',
      '....tttkkttt....',
      '....tttkkttt....',
      '...tttttttttt...',
      '...ttttkktttt...',
      '..tttttkkttttt..',
      '..tttttttttttt..',
      '.tttttttttttttt.',
      '................',
      '................',
    ],
  ],
  palette: { t: '#ffcf3f', k: '#2b2b35' },
};

const SPEAKER_ON: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '.......ss.......',
      '......sss..w....',
      '.....ssss.w.w...',
      '..sssssss..w.w..',
      '..sssssss.w.w.w.',
      '..sssssss.w.w.w.',
      '..sssssss.w.w.w.',
      '..sssssss..w.w..',
      '.....ssss.w.w...',
      '......sss..w....',
      '.......ss.......',
      '................',
      '................',
    ],
  ],
  palette: { s: '#e8e0d0', w: '#9fd0ff' },
};

const SPEAKER_OFF: SpriteDefinition = {
  frames: [
    [
      '................',
      '................',
      '................',
      '.......ss.......',
      '......sss.......',
      '.....ssss.......',
      '..sssssss.r..r..',
      '..sssssss..rr...',
      '..sssssss..rr...',
      '..sssssss.r..r..',
      '..sssssss.......',
      '.....ssss.......',
      '......sss.......',
      '.......ss.......',
      '................',
      '................',
    ],
  ],
  palette: { s: '#8a8f98', r: '#e04a3a' },
};

export const UI_ICONS: Record<string, SpriteDefinition> = {
  coin: COIN,
  crate: CRATE,
  battery: BATTERY,
  dynamite: { frames: [ENTITY_SPRITES.dynamite.frames[0]], palette: ENTITY_SPRITES.dynamite.palette },
  flare: { frames: [ENTITY_SPRITES.flare.frames[0]], palette: ENTITY_SPRITES.flare.palette },
  depth: DEPTH,
  pickaxe: PICKAXE,
  lightning: LIGHTNING,
  blast: BLAST,
  star: STAR,
  x_key: X_KEY,
  pause: PAUSE,
  plus: PLUS,
  drill_down: DRILL_DOWN,
  warning: WARNING,
  speaker_on: SPEAKER_ON,
  speaker_off: SPEAKER_OFF,
  z_key: Z_KEY,
  battery_wide: BATTERY_WIDE,
  arrows: ARROWS,
};

// ------------------------------------------------------------------ emblem

/** 64x64 brilliant-cut diamond for the title screen: a flat table, a bright
 * girdle waist and a faceted pavilion tapering to the point, animated with a
 * looping "bling" twinkle across the facets. */
export const EMBLEM: SpriteDefinition = {
  frames: [
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollblllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllwlllelllebbbegggeggggo..................',
      '..................ollblwwwlbllllebbbbeggggegggo.................',
      '.................ollllllwlllllllebbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolellllllbellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbegggggggggweddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggwwwdddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggwdddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggedddddddo...............',
      '.................olllllllbbbbbbbegggggggdddddddo................',
      '..................oolllllebbbbbbeggggggedddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllebbbbbegggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllelllelllebbbegggeggggo..................',
      '..................olllellllellllebbbbeggggeggbo.................',
      '.................ollllllllllllllebbbbbgggggglwlo................',
      '...............oollellllllllllllebbbbbbggggbwwwboo..............',
      '..............oolelllllllellllllebbbbbbegggglwlegoo.............',
      '.............ollelllllllelllllllebbbbbbbeggggbggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbeggggggggggeddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggedddddddo...............',
      '.................olllllllbbbbbbbegggggggdddddddo................',
      '..................oolllllebbbbbbeggggggedddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllebbbbbegggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllelllelllebbbegggeggggo..................',
      '..................olllellllellllebbbbeggggegggo.................',
      '.................ollllllllllllllebbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolelllllllellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olelllllwllellllllllebbbbbbbbeggggggggego...........',
      '...........oeelllllwwwelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllweelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbeggggggggggeddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbbggggggggeddddddddo.............',
      '...............olllllllebbbbbbbblggggggggedddddddo..............',
      '................olllllllebbbbbblwlggggggedddddddo...............',
      '.................olllllllbbbbblwwwlbggggdddddddo................',
      '..................oolllllebbbbblwlgggggedddddoo.................',
      '...................oolllllbbbbbblggggggdddddoo..................',
      '.....................ollllebbbbbbgggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllelllelllebbbegggeggggo..................',
      '..................olllellllellllebbbbeggggegggo.................',
      '.................ollllllllllllllebbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolelllllllellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbeggggggggggeddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggedddddddo...............',
      '.................olllllllbbbbbbbegggggggdddddddo................',
      '..................oolllllebbbbbbeggggggedddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllebbbbbegggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllelllelllebbbegggeggggo..................',
      '..................olllellllellllebbbbeggggegggo.................',
      '.................ollllllllllllllebbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolelllllllellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbegggbggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeeglwlgggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbebwwwbggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbelwlggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllblllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbeggggggggggeddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggedddddddo...............',
      '.................olllllllbbbbbbbegggggggdddddddo................',
      '..................oolllllebbbbbbeggggggedddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllewbbbbegggggeddddo....................',
      '......................olllwwwbbbegggggddddo.....................',
      '.......................olllwbbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllelllelllebbbegggeggggo..................',
      '..................olllellllellllebbbbeggggegggo.................',
      '.................ollllllllllllllebbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolelllllllellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebblwlbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebwwwbbbbbbeggggggggggeddddddddddo.........',
      '...........ollllllllleblwlbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggedddddddo...............',
      '.................olllllllbbbbbbbegggggggdddddddo................',
      '..................oolllllebbbbbbeggggggedddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllebbbbbegggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oolllllllbllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllwlllllllllgo....................',
      '....................ollllllllblwwwlbllllllggo...................',
      '...................ollllelllelllwlbbegggeggggo..................',
      '..................olllellllelllllbbbbeggggegggo.................',
      '.................ollllllllllllllbbbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolelllllllellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbeggggggggggeddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggwdddddddo...............',
      '.................olllllllbbbbbbbeggggggwwwdddddo................',
      '..................oolllllebbbbbbeggggggewddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllebbbbbegggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '........................oollllllllllllloo.......................',
      '.......................oollllllllllllllloo......................',
      '......................olllllllllllllllllllo.....................',
      '.....................ollllllllllllllllllllgo....................',
      '....................olllllllllllllllllllllggo...................',
      '...................ollllelllelllebbbegggeggggo..................',
      '..................olllellllellllebbbbeggggegggo.................',
      '.................ollllllllllllllebbbbbgggggggggo................',
      '...............oollellllllllllllebbbbbbggggggeggoo..............',
      '..............oolelllllllellllllebbbbbbegggggggegoo.............',
      '.............ollelllllllelllllllebbbbbbbegggggggeggo............',
      '............olellllllllellllllllebbbbbbbbeggggggggego...........',
      '...........oeellllllllelllllllllebbbbbbbbbeggggggggeeo..........',
      '..........oellllllllleelllllllllebbbbbbbbbeegggggggggeo.........',
      '.........olllllllllllellllllllllebbbbbbbbbbegggggggggggo........',
      '........olllllllllllelllllllllllebbbbbbbbbbbegggggggggggo.......',
      '......oollllllllllllllllllllllllllllllllllllllllllllllllloo.....',
      '........olllllllllleebbbbbbbbbbbegggggggggggeeddddddddddo.......',
      '.........ollllllllllebbbbbbbbbbbegggggggggggeddddddddddo........',
      '..........ollllllllllebbbbbbbbbbeggggggggggeddddddddddo.........',
      '...........olllllllllebbbbbbbbbbeggggggggggedddddddddo..........',
      '............olllllllllebbbbbbbbbegggggggggedddddddddo...........',
      '.............ollllllllebbbbbbbbbegggggggggeddddddddo............',
      '..............ollllllllebbbbbbbbeggggggggeddddddddo.............',
      '...............olllllllebbbbbbbbeggggggggedddddddo..............',
      '................olllllllebbbbbbbegggggggedddddddo...............',
      '.................olllllllbbbbbbbegggggggdddddddo................',
      '..................oolllllebbbbbbeggggggedddddoo.................',
      '...................oolllllbbbbbbeggggggdddddoo..................',
      '.....................ollllebbbbbegggggeddddo....................',
      '......................ollllbbbbbegggggddddo.....................',
      '.......................olllebbbbeggggedddo......................',
      '........................olllbbbbeggggdddo.......................',
      '.........................olllbbbegggdddo........................',
      '..........................ollbbbegggddo.........................',
      '...........................ollbbeggddo..........................',
      '............................olbbeggdo...........................',
      '.............................olbegdo............................',
      '..............................obego.............................',
      '...............................ooo..............................',
      '................................o...............................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
  ],
  palette: { o: '#0e2f38', e: '#1c5b68', d: '#2a9db3', g: '#46c6d9', b: '#83e7f3', l: '#c4f6fb', w: '#ffffff' },
};
